"""Initial Migration.

Revision ID: f21038818259
Revises: 
Create Date: 2020-01-28 00:21:35.725941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21038818259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_number', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('env', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'PENDING', 'RUNNING', 'FAILED', 'COMPLETED', name='deploystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_env'), 'deployments', ['env'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_env'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('repositories')
    # ### end Alembic commands ###
